data = [
    {"text": "Poor eye contact, or staring from unusual angle"},
    {"text": "Inappropriately anxious, scared"},
    {"text": "Lack of curiosity about the environment"},
    {"text": "Inappropriate crying or laughing"},
    {"text": "Hates crowds, difficulties in restaurants and supermarkets"},
    {"text": "Lack of ability to imitate"},
    {"text": "Produces unusual noises or infantile squeals"},
    {"text": "Can not sustain conversation"},
    {"text": "Speaks same to kids, adults, objects (can not differentiate)"},
    {"text": "Stubborn about rituals and routines; resists to change"},
    {
        "text": "Age of child (in years)",
        "type": "number",
        "input": {"step": 1, "min_value": 2},
    },
    {
        "text": "Gender",
        "type": "select",
        "options": ("Male", "Female"),
    },
    {
        "text": "Ethnicity",
        "type": "select",
        "options": (
            "Middle Eastern",
            "Black",
            "White European",
            "Asian",
            "South Asian",
            "Others",
            "Pacifica",
            "Middle Eastern",
            "Mixed",
        ),
    },
    {"text": "Jaundice at birth"},
    {
        "text": "Relation who took the test",
        "type": "select",
        "options": (
            "Parent",
            "Relative",
            "Self",
            "Health care professional",
            "Others",
        ),
    },
    {"text": "Autism in blood relations"},
    {
        "text": "Age description",
        "type": "select",
        "options": ("Toddler", "Child", "Teenager", "Adult"),
    },
]
